version: "3.9"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "4444:444"
  apache:
    image: httpd:alpine
    ports:
      - "8080:80"
    volumes:
    - ./apache/www:/var/www/html
  datase: 
    image: mysql:latest
  hacker: 
    build: Toolkit/
